import {useState,useEffect} from 'react';
import {Search,ArrowRight,ChevronRight,Menu,X} from 'react-feather';
import '@fontsource/dm-sans/400.css';import '@fontsource/dm-sans/500.css';import '@fontsource/playfair-display/700.css';
const crops=[['Paddy','Stronger plants for a brighter harvest.'],['Coconut','Nourishing growth for lasting value.'],['Banana','Healthy plants. Stronger tomorrows.']];
const areas=['Crop nutrition','Soil care','Plant health'];
export function App(){const[menu,setMenu]=useState(false),[search,setSearch]=useState(false),[term,setTerm]=useState(''),[selected,setSelected]=useState(null),[interest,setInterest]=useState('General enquiry'),[draft,setDraft]=useState(''),[copied,setCopied]=useState(false);
useEffect(()=>{if(!selected&&!search)return;const previous=document.activeElement;const modal=document.querySelector('.modal');const elements=()=>[...modal.querySelectorAll('button,input,select,textarea,a[href]')];elements()[0]?.focus();function keys(e){if(e.key==='Escape'){setSelected(null);setSearch(false);}if(e.key==='Tab'){const f=elements(),first=f[0],last=f[f.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}}document.addEventListener('keydown',keys);return()=>{document.removeEventListener('keydown',keys);previous?.focus()}},[selected,search]);
function enquire(value){setInterest(value);setSelected(null);document.getElementById('contact').scrollIntoView({behavior:'smooth'});}
return <><header><a href="#home" className="brand"><img src="/assets/logo.png" alt="Agriya Agro Tech"/></a><nav className={menu?'open':''} aria-label="Main navigation">{['Home','About','Products','Crop Solutions','Contact'].map((n,i)=><a key={n} className={i===0?'active':''} href={'#'+['home','about','products','crops','contact'][i]} onClick={()=>setMenu(false)}>{n}</a>)}</nav><button className="icon" aria-label="Search website" onClick={()=>setSearch(true)}><Search size={22}/></button><button className="icon mobile" aria-label="Toggle menu" aria-expanded={menu} onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>
<main><section className="hero" id="home"><img className="hero-image" src="/assets/hero.webp" alt="Farmer overlooking sunlit paddy fields and coconut palms"/><img className="hero-wave" src="/assets/wave.webp" alt=""/><div className="hero-panel"><p className="eyebrow">GROWER FIRST</p><h1>Every field.<br/>New possibilities.</h1><p className="intro">Explore agricultural care with Agriya Agro Tech. Start with your crop, understand your field and discover your next step.</p><div className="actions"><a className="button" href="#products">Explore products <ChevronRight size={19}/></a><a className="button outline" href="#contact">Contact us</a></div></div></section>
<section className="crop-section" id="crops"><h2>Start with your crop</h2><p>Explore agricultural care for the crops you grow.</p><div className="crop-grid">{crops.map(([name,desc])=><button className="crop" key={name} onClick={()=>setSelected(name)}><img src={'/assets/'+name.toLowerCase()+'.webp'} alt={name+' crop'}/><div><h3>{name}</h3><p>{desc}</p></div><span className="circle"><ChevronRight/></span></button>)}</div></section>
<section className="about-section" id="about"><div><p className="eyebrow">ABOUT AGRIYA</p><h2>Closer to the field.<br/>Connected to you.</h2></div><div><p>Welcome to Agriya Agro Tech. Explore crop nutrition, soil care and plant health, and begin a conversation about your agricultural needs.</p><p>Farmers and dealers can use this website to discover areas of care and prepare a product or partnership enquiry.</p><a className="text-link" href="#contact">Let’s connect <ArrowRight size={20}/></a></div></section>
<section id="products" className="product-section"><p className="eyebrow">EXPLORE AGRICULTURAL CARE</p><h2>Find your area of care</h2><p>Browse a category to prepare a more focused enquiry.</p><div className="area-grid">{areas.map((n,i)=><button key={n} onClick={()=>setSelected(n)}><span className="index">0{i+1}</span><h3>{n}</h3><p>{['Crop stage, leaf appearance and nutrition questions.','Soil conditions, testing and field preparation.','Crop observations and questions from your field.'][i]}</p><ArrowRight size={23}/></button>)}</div><p className="small">Confirmed product names, photographs and specifications will be added to this catalogue.</p></section>
<section className="contact-section" id="contact"><div><p className="eyebrow">GROW CONNECTIONS</p><h2>Let’s talk about<br/>your next season.</h2><p>Tell us about your crop or dealer enquiry.</p><p className="small">Prepare and copy your enquiry below. Sending will be enabled when company contact details are added.</p></div><form onSubmit={e=>{e.preventDefault();const d=new FormData(e.target);setDraft('Agriya Agro Tech enquiry\nName: '+d.get('name')+'\nPhone: '+d.get('phone')+'\nInterest: '+interest+'\nLocation: '+d.get('location')+'\nMessage: '+d.get('message'));setCopied(false)}}><label>Name<input required name="name" autoComplete="name" maxLength="100"/></label><label>Phone<input required name="phone" type="tel" autoComplete="tel" maxLength="30"/></label><label>Interest<select value={interest} onChange={e=>setInterest(e.target.value)}>{['General enquiry',...crops.map(c=>c[0]),...areas,'Dealer partnership'].map(n=><option key={n}>{n}</option>)}</select></label><label>Town / district<input name="location" maxLength="150"/></label><label className="full">Your enquiry<textarea name="message" required maxLength="2000"/></label><button className="button full">Prepare enquiry <ArrowRight size={18}/></button>{draft&&<div className="full draft" aria-live="polite"><p>Your enquiry is ready. It has not been sent.</p><pre>{draft}</pre><button type="button" className="button outline" onClick={async()=>{try{await navigator.clipboard.writeText(draft);setCopied(true)}catch{setCopied(false)}}}>{copied?'Copied':'Copy enquiry'}</button></div>}</form></section></main>
<footer><img src="/assets/logo.png" alt="Agriya Agro Tech"/><p>Rooted in agriculture. Growing connections.</p><p>© {new Date().getFullYear()} Agriya Agro Tech</p></footer>
{selected&&<div className="modal-backdrop" onClick={()=>setSelected(null)}><section className="modal" role="dialog" aria-modal="true" aria-label={selected+' information'} onClick={e=>e.stopPropagation()}><button className="icon close" aria-label="Close details" onClick={()=>setSelected(null)}><X/></button><p className="eyebrow">YOUR FIELD, YOUR NEXT STEP</p><h2>{selected}</h2><p>{crops.some(c=>c[0]===selected)?'Share the crop age, growing stage, leaf appearance and field conditions with your enquiry.':'Tell us about your field conditions and the information you need for this area of care.'}</p><p className="small">Product availability and application details require company confirmation.</p><button className="button" onClick={()=>enquire(selected)}>Prepare an enquiry <ArrowRight size={18}/></button></section></div>}
{search&&<div className="modal-backdrop"><section className="modal" role="dialog" aria-modal="true" aria-label="Search website"><button className="icon close" aria-label="Close search" onClick={()=>setSearch(false)}><X/></button><h2>What are you looking for?</h2><label>Search crop or category<input autoFocus value={term} onChange={e=>setTerm(e.target.value)} placeholder="Try coconut or soil care"/></label><div className="results">{term && ![...crops.map(c=>c[0]),...areas,'About Agriya','Dealer partnership'].some(n=>n.toLowerCase().includes(term.toLowerCase())) && <p>No matches. Try a crop or category name.</p>}{[...crops.map(c=>c[0]),...areas,'About Agriya','Dealer partnership'].filter(n=>n.toLowerCase().includes(term.toLowerCase())).map(n=><button key={n} onClick={()=>{setSearch(false);if(n==='About Agriya')document.getElementById('about').scrollIntoView();else if(n==='Dealer partnership')enquire(n);else setSelected(n)}}>{n}<ArrowRight size={18}/></button>)}</div></section></div>}</>}
